name: Update

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 16 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:
          script: |
            const script = require(".github/workflows/update/script.js");
            await script({ github, context, core, glob, io, exec, require });
      - uses: stefanzweifel/git-auto-commit-action@v5
